export interface ValidationError {
    code: string;
    severity: "error" | "warning";
    title: string;
    message: string;
    hint?: string;
    line?: number;
}

export interface ValidationResult {
    ok: boolean;
    errors: ValidationError[];
}

export function validateTsxCode(code: string): ValidationResult {
    const errors: ValidationError[] = [];

    // 1. Empty Check
    if (!code || code.trim().length === 0) {
        return {
            ok: false,
            errors: [
                {
                    code: "empty-code",
                    severity: "error",
                    title: "No code found",
                    message: "The editor is empty. You need to paste the TSX code generated by Claude.",
                    hint: "Copy the code from Claude and paste it here to begin.",
                },
            ],
        };
    }

    // 2. Export Check
    if (!code.includes("export default")) {
        errors.push({
            code: "missing-export",
            severity: "error",
            title: "Missing default export",
            message: "Your code must have an 'export default' component for Remotion to render.",
            hint: "Add 'export default function MyComponent() { ... }' to your main function.",
        });
    }

    // 3. Remotion Imports Check
    if (!code.includes("remotion")) {
        errors.push({
            code: "missing-remotion",
            severity: "warning",
            title: "Remotion imports missing",
            message: "The code doesn't seem to import from 'remotion'. This might cause preview issues.",
            hint: "Make sure to import { AbsoluteFill } from 'remotion'.",
        });
    }

    // 4. Forbidden Keywords (Safety)
    const forbidden = [
        { key: "fs.", title: "File system access" },
        { key: "child_process", title: "Process execution" },
        { key: "process.env", title: "Environment variable access" },
        { key: "require(", title: "Old module system usage" },
    ];

    forbidden.forEach((f) => {
        if (code.includes(f.key)) {
            errors.push({
                code: `forbidden-${f.key}`,
                severity: "error",
                title: f.title,
                message: `Your code uses '${f.key}', which is not allowed in browser-based TSX.`,
                hint: "Remove any server-side or node.js specific code.",
            });
        }
    });

    // 5. Invalid Return Check
    if (!code.includes("return (") && !code.includes("return <")) {
        errors.push({
            code: "missing-return",
            severity: "error",
            title: "Invalid JSX Return",
            message: "We couldn't find a valid JSX return statement in your component.",
            hint: "Components must return JSX, like 'return <AbsoluteFill>...</AbsoluteFill>'.",
        });
    }

    // 6. External Imports (HTTP)
    if (code.includes("import('http") || code.includes("import(\"http")) {
        errors.push({
            code: "external-import",
            severity: "error",
            title: "External runtime import",
            message: "Dynamic imports from external URLs are not supported for safety.",
            hint: "Use only local imports or standard installed libraries.",
        });
    }

    // 7. Size Check
    if (code.length > 200 * 1024) {
        errors.push({
            code: "file-size",
            severity: "warning",
            title: "Large file detected",
            message: "This file is over 200KB. It may cause performance issues during preview.",
            hint: "Try to split the code or reduce large embedded assets like base64 images.",
        });
    }

    return {
        ok: !errors.some((e) => e.severity === "error"),
        errors,
    };
}
